# -*- coding: utf-8 -*-
"""bioStatsAssignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEgVsld0zKFLakvMyZ_8rdtXgCgztLX9
"""

#Roberto Borges
#101255891

import pandas as pd
import numpy as np

READ = pd.read_csv("/content/biostats.csv")
READ

age = np.array(READ["Age"])
age

ageAvg = np.average(READ["Age"])
ageAvg

standard_age = np.std(age)
standard_age

minimumAge = np.min(age)
minimumAge

maxAge = np.max(age)
maxAge


percentiles = np.percentile(age, 30)
percentiles

med = np.median(age)
med

percentiles2 = np.percentile(age, 70)
percentiles2

import matplotlib.pyplot as plt

ages = df["Age"]

bins = [20, 30, 40, 50, 60]

plt.hist(ages, bins, histtype='bar', rwidth = 0.8, color = 'green')

plt.xlabel('Ages')
plt.ylabel('No. of Employees')

plt.title('Age Distribution - By Roberto Borges')
plt.show()